import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import Head from 'next/head';
import Script from 'next/script';
import "./globals.css";

export const metadata: Metadata = {
  title: "Folya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <title>
          Folya
        </title>
        <meta name="description" content="Folya - Optimize your workflow and enhance productivity" />
        <meta name="keywords" content="Folya, healthcare, management, productivity" />
        <meta name="keywords" content="" />
        <meta name="description" content="Simplifiez votre quotidien avec Folya, la plateforme tout-en-un conçue pour les professionnels de santé. Gérez vos rendez-vous, vos dossiers patients et optimisez votre organisation grâce à des outils intuitifs et personnalisés." />
        <link rel="canonical" href="https://www.folya.co/" />
        <meta property="og:locale" content="fr_FR" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Folya : Votre assistant personnel pour une gestion efficace de votre cabinet" />
        <meta property="og:description" content="Simplifiez votre quotidien avec Folya, la plateforme tout-en-un conçue pour les professionnels de santé. Gérez vos rendez-vous, vos dossiers patients et optimisez votre organisation grâce à des outils intuitifs et personnalisés." />
        <meta property="og:url" content="https://www.folya.co/" />
        <meta property="og:site_name" content="Folya - La solution pour les professionnels de santé" />
        <meta property="article:modified_time" content="2024-09-06T08:53:11+00:00" />
        {/* Always force latest IE rendering engine */}
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        {/* Mobile Specific Meta */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Favicon */}
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        {/* Custom style CSS */}
        <link rel="stylesheet" href="styles/all.min.css" />
        {/* Responsive CSS */}
        <link rel="stylesheet" href="styles/responsive.css" />
      </Head>
      <body>

        <Navbar />
        <main className="relative overflow-hidden">
          {children}
        </main>
        <Footer />
        <Script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" ></Script>
        {/* <Script src="js/jquery-2.2.4.min.js"></Script> */}
        <Script src="js/jquery-ui.min.js"></Script>
        <Script src="js/jquery.magnific-popup.min.js"></Script>
        <Script src="js/jquery.slicknav.min.js"></Script>
        <Script src="js/jquery.sticky.js"></Script>
        <Script src="js/main.js"></Script>
        <Script src="js/script.js"></Script>
        <Script src="js/owl.carousel.min.js"></Script>
      </body>
    </html>
  );
}
